---
platform: linux
image_resource:
  type: docker-image
  source: {repository: suranagivinod/ubuntu-unzip}
params:
  target:
  client:
  client_secret:
  ca_cert:
  jumpbox_url:
  jumpbox_ssh_key:
inputs:
- name: ci-pipeline-git
run:
  path: ci-pipeline-git/load-bosh-vars-example/bin/load-bosh-vars.sh
