---
resources:
- name: ci-pipeline-git
  type: git
  source:
    uri: git@github.com:niharbabu99/concourse-examples.git
    branch: master

jobs:
- name: bosh-load-test
  serial: true
  plan:
  - get: ci-pipeline-git
  - task: check-load
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: suranagivinod/ubuntu-unzip
      inputs:
      - name: ci-pipeline-git
      params:
       target: ((director_address))
       client: ((bosh_client))
       client_secret: ((bosh_client_pwd))
       ca_cert: ((bosh_ca_cert))
       jumpbox_url: ((jumpbox_url))
       jumpbox_ssh_key: ((jumpbox_key))
      run:
       path: bash
       args:
       - -exec
       - |
         source ci-pipeline-git/bin/load-bosh-vars.sh
         bosh deployments
